<?php

declare(strict_types=1);

namespace Tests\Unit\Services\Domain\QrCode;

use HiEvents\Services\Domain\QrCode\QrCodeService;
use Tests\TestCase;

class QrCodeServiceTest extends TestCase
{
    private const PNG_MAGIC = "\x89PNG\r\n\x1a\n";

    private QrCodeService $service;

    protected function setUp(): void
    {
        parent::setUp();
        $this->service = new QrCodeService();
    }

    public function test_generates_non_empty_png_bytes(): void
    {
        $bytes = $this->service->generatePng('test-payload');

        $this->assertNotEmpty($bytes, 'Generated PNG bytes should not be empty');
        $this->assertSame(
            self::PNG_MAGIC,
            substr($bytes, 0, 8),
            'Generated bytes should begin with the PNG magic header',
        );
    }

    public function test_generates_different_output_for_different_input(): void
    {
        $first = $this->service->generatePng('payload-one');
        $second = $this->service->generatePng('payload-two');

        $this->assertNotSame(
            $first,
            $second,
            'Different payloads should produce different PNG bytes',
        );
    }

    public function test_size_parameter_changes_output_size(): void
    {
        $small = $this->service->generatePng('size-payload', 100);
        $large = $this->service->generatePng('size-payload', 800);

        $this->assertNotSame(
            $small,
            $large,
            'Different size hints should produce different PNG bytes',
        );

        $smallInfo = getimagesizefromstring($small);
        $largeInfo = getimagesizefromstring($large);

        $this->assertIsArray($smallInfo, 'Small PNG should be decodable by getimagesizefromstring()');
        $this->assertIsArray($largeInfo, 'Large PNG should be decodable by getimagesizefromstring()');

        $this->assertGreaterThan(
            $smallInfo[0],
            $largeInfo[0],
            'Larger size hint should yield a wider image',
        );
        $this->assertGreaterThan(
            $smallInfo[1],
            $largeInfo[1],
            'Larger size hint should yield a taller image',
        );
    }
}
